import '../styles/globals.css'
import {Navigation} from './components/Navegation';

export const metadata = {
  title: 'Poke-Api',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">             
      <body>
        <Navigation/>
        {children}
      </body>
    </html>
  )
}
